PROJ_NAME =test
CC=gcc
SRCS=uart_pc.o main_uart.o spi_pc.o

DRAPEAU =-Wall

all:$(PROJ_NAME).pc

$(PROJ_NAME).pc: $(SRCS)
	$(CC) $(DRAPEAU) -o $(PROJ_NAME).pc $(SRCS) $(LDFLAGS) 

main_uart.o: main_uart.c
	$(CC) $(DRAPEAU) -c main_uart.c

uart_pc.o: uart_pc.c
	$(CC) $(DRAPEAU) -c uart_pc.c

spi_pc.o: spi_pc.c
	$(CC) $(DRAPEAU) -c spi_pc.c

clean:
	rm *.o $(PROJ_NAME).pc
